import { Fab,
  Card ,
  Chip ,
  Tabs ,
  Menu ,
  Link ,
  Lists ,
  Table ,
  Alert ,
  Badge ,
  Paper ,
  Input ,
  Radio ,
  Drawer,
  Dialog,
  Avatar,
  Rating,
  Slider,
  Button,
  Switch,
  Select,
  SvgIcon ,
  Tooltip ,
  Popover ,
  Stepper ,
  DataGrid,
  Skeleton,
  Backdrop,
  Progress,
  Timeline,
  TreeView,
  Checkbox,
  Accordion ,
  Typography ,
  Pagination ,
  Breadcrumbs ,
  ButtonGroup ,
  CssBaseline ,
  Autocomplete ,
  ToggleButton ,
  ControlLabel ,
  LoadingButton, 
  TextField, } from "./overrides";


// ----------------------------------------------------------------------

export default function ComponentsOverrides(theme) {
  return Object.assign(
    Fab(theme),
    Tabs(theme),
    Chip(theme),
    Card(theme),
    Menu(theme),
    Link(theme),
    Input(theme),
    Radio(theme),
    Badge(theme),
    Lists(theme),
    Table(theme),
    Paper(theme),
    Alert(theme),
    Switch(theme),
    Select(theme),
    Button(theme),
    Rating(theme),
    Dialog(theme),
    Avatar(theme),
    Slider(theme),
    Drawer(theme),
    Stepper(theme),
    Tooltip(theme),
    Popover(theme),
    SvgIcon(theme),
    Checkbox(theme),
    DataGrid(theme),
    Skeleton(theme),
    Timeline(theme),
    TreeView(theme),
    Backdrop(theme),
    Progress(theme),
    Accordion(theme),
    Typography(theme),
    Pagination(theme),
    ButtonGroup(theme),
    Breadcrumbs(theme),
    CssBaseline(theme),
    Autocomplete(theme),
    ControlLabel(theme),
    ToggleButton(theme),
    LoadingButton(theme),
    TextField(theme)
  );
}
